[package]
name = "twitch_api"
version = "0.1.0"
authors = ["David Blajda <blajda@hotmail.com>"]
edition = "2018"

[dependencies]
reqwest = "0.9.5"
futures = "0.1.25"
tokio = "0.1.13"
dotenv = "0.13.0"
serde = "1.0.81"
serde_json = "1.0.33"
