name: Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: Swatinem/rust-cache@v1.4.0
    - uses: actions/checkout@v2
    - name: Install latest nightly
      uses: actions-rs/toolchain@v1
      with:
          toolchain: nightly
          override: true
    - name: Build
      run: cargo build --verbose
    - name: Setup mock Twitch Api Server
      run: |
        mkdir twitch-cli
        curl -L https://github.com/twitchdev/twitch-cli/releases/download/v1.1.6/twitch-cli_1.1.6_Linux_x86_64.tar.gz -o twitch-cli.tar.gz
        tar -C twitch-cli -xf twitch-cli.tar.gz
        ls twitch-cli
        ./twitch-cli/twitch-cli_*/twitch mock-api start &
    - name: Cargo test
      run: |
        cargo test
